**Punto 1**

Implementación de la función *multiplicación matricial* en base a valores parametrizados. Adicionalmente se generaron arreglos de prueba para corroborar el correcto funcionamiento de esta función.

In [1]:
import numpy as np

#Punto 1: Función multiplicación matricial
def f(A,B,c,d):
    k1=A**c
    k2=B**d
    result='No se puede ejecutar la operación'
    
    if (k1.shape[1]==k2.shape[0]):
        result=np.dot(k1,k2)
        return result
    else:
        return result
    
#Valores aleatorios de prueba
A=np.random.randint(10, size=(4,2))
A=np.array(A)

B=np.random.randint(15, size=(2,3))
B=np.array(B)

exp=np.array([2,1])

print(f(A,B,exp[0],exp[1]))

[[  93  291   95]
 [ 108  432   72]
 [ 648 1863  729]
 [ 153  531  135]]


**Punto 2.1**

A partir de la función desarrollada y valores caraterísticos para *(A,B,c,d)* se lleva a cabo las operaciones matriciales solicitadas.

In [2]:
A=[[0.1,2],[2,0.1]]
A=np.array(A)

B=[[1,2,3],[4,5,6]]
B=np.array(B)

C=[[5/3,2/3],[5/3,2/3]]
C=np.array(C)

i=f(A,np.transpose(B),1,1)
print('i= ',i)

ii=f(A,B,2,1)
print('ii= ',ii)

iii=f(B,C,1,3)
print('iii= ',iii)

iv=f(np.transpose(B),C,1,4)
print('iv= ',iv)

i=  No se puede ejecutar la operación
ii=  [[16.01 20.02 24.03]
 [ 4.04  8.05 12.06]]
iii=  No se puede ejecutar la operación
iv=  [[38.58024691  0.98765432]
 [54.01234568  1.38271605]
 [69.44444444  1.77777778]]


**Punto 2.2**

Se desarrolla un código que permite al usuario digitar el valor numérico entero *(c,d)* que se solicita en la función *f*. 

In [3]:
flag=[0,0]
while flag[0]==0:
    try:
        c=float(input('Introduzca un valor numérico: ')) 
        flag[0]=1
    except ValueError:
        print('Debe ser un valor numérico')

while flag[1]==0:
    try:
        d=float(input('Introduzca un valor numérico: ')) 
        flag[1]=1
    except ValueError:
        print('Debe ser un valor numérico')
        
print(f(A,B,c,d))

Introduzca un valor numérico:  2
Introduzca un valor numérico:  %


Debe ser un valor numérico


Introduzca un valor numérico:  1


[[16.01 20.02 24.03]
 [ 4.04  8.05 12.06]]


**Punto 3**

Partiendo de una matriz numérica definida como *A* se determina las matrices obtenidas según operaciones sucesivas. 

In [5]:
A=[[3,2,2],[-2,1,4],[1,0,3],[5,-2,1]]
A=np.array(A)

#Caso 1
op1=np.array(A[0][:]*1/4)
R1=np.vstack([op1,A[1:][:]])
print('Multiplicando la fila 1 de A por 1/4 da como resultado: ',R1)

#Caso 2
R2=R1
R2[1][:]=np.add((R2[0][:]*3),R2[1][:])
print('Sumando 3 veces la fila 1 del nuevo A a la fila 2: ',R2)

#Caso 3
R3=R2
R3[2][:]=np.add(np.negative(R3[0][:]),R3[2][:])
print('Sumando (-1) veces la fila 1 del nuevo A a la fila 3: ',R3)

#Caso 4
R4=R3
R4[3][:]=np.add(np.negative(R3[0][:]*5),R3[3][:])
print('Sumando (-5) veces la fila 1 del nuevo A a la fila 4: ',R4)

#Caso 5
R5=R4
R5[[1,3]]=R5[[3,1]]
print('Intercambiar filas 2 y 4: ',R4)


Multiplicando la fila 1 de A por 1/4 da como resultado:  [[ 0.75  0.5   0.5 ]
 [-2.    1.    4.  ]
 [ 1.    0.    3.  ]
 [ 5.   -2.    1.  ]]
Sumando 3 veces la fila 1 del nuevo A a la fila 2:  [[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 1.    0.    3.  ]
 [ 5.   -2.    1.  ]]
Sumando (-1) veces la fila 1 del nuevo A a la fila 3:  [[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 5.   -2.    1.  ]]
Sumando (-5) veces la fila 1 del nuevo A a la fila 4:  [[ 0.75  0.5   0.5 ]
 [ 0.25  2.5   5.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 1.25 -4.5  -1.5 ]]
Intercambiar filas 2 y 4:  [[ 0.75  0.5   0.5 ]
 [ 1.25 -4.5  -1.5 ]
 [ 0.25 -0.5   2.5 ]
 [ 0.25  2.5   5.5 ]]
